import 'package:cloud_firestore/cloud_firestore.dart';

import 'package:keyframes_app/data/models/enums.dart';
import 'package:keyframes_app/data/models/order.dart';
import 'package:keyframes_app/data/models/order_draft.dart';
import 'package:keyframes_app/data/repositories/order_repository.dart';
import 'package:keyframes_app/features/order/default_order_service.dart';

/// Resolves the id of the currently authenticated user (the "client").
///
/// Injected into [FirebaseOrderRepository] so the repository stays decoupled
/// from any concrete auth backend: production wiring supplies a function that
/// reads `FirebaseAuth.instance.currentUser?.uid`, while tests can supply a
/// fixed id. Returns `null` when no user is signed in.
typedef CurrentUserIdProvider = String? Function();

/// Cloud Firestore-backed implementation of [OrderRepository].
///
/// Orders live in a single top-level `orders` collection. The Firestore
/// document id is the canonical [Order.id]; it is generated by Firestore when
/// an order is created and is never persisted inside the document body.
///
/// All lifecycle rules are delegated to the injected [DefaultOrderService] so
/// the same state machine applies regardless of backend:
///
/// * [createOrder] builds the initial `pending` [Order] via
///   [DefaultOrderService.buildInitialOrder] (using the new doc-ref id and the
///   current user as `clientId`), persists it, then fires the admin
///   notification hook (Requirements 8.6, 8.7).
/// * [updateStatus] reads the current order, computes the next order with
///   [DefaultOrderService.appendStatusEvent] (which validates the transition
///   and appends one timeline event), persists the new `status`/`timeline`, and
///   notifies the owning client. Illegal transitions surface as an
///   [InvalidOrderTransitionException] and leave the stored order untouched
///   (Requirements 10A.1, 10A.4, 10A.5).
/// * [watchClientOrders] scopes the stream to a single `clientId`
///   (Requirement 10.3); [watchAllOrders] backs the admin view with an optional
///   status filter (Requirement 11.2); [watchOrder] streams one order
///   (Requirements 10.1, 10.3).
class FirebaseOrderRepository implements OrderRepository {
  /// Creates a repository over the given [firestore] (defaults to the singleton
  /// [FirebaseFirestore.instance]), delegating lifecycle logic to [orderService]
  /// and sourcing the acting client id from [currentUserId].
  FirebaseOrderRepository({
    required DefaultOrderService orderService,
    required CurrentUserIdProvider currentUserId,
    FirebaseFirestore? firestore,
  })  : _orderService = orderService,
        _currentUserId = currentUserId,
        _firestore = firestore ?? FirebaseFirestore.instance;

  /// Name of the top-level Firestore collection holding orders.
  static const String collectionPath = 'orders';

  final DefaultOrderService _orderService;
  final CurrentUserIdProvider _currentUserId;
  final FirebaseFirestore _firestore;

  CollectionReference<Map<String, dynamic>> get _orders =>
      _firestore.collection(collectionPath);

  // ---------------------------------------------------------------------------
  // Writes
  // ---------------------------------------------------------------------------

  @override
  Future<Order> createOrder(OrderDraft draft) async {
    final String? clientId = _currentUserId();
    if (clientId == null || clientId.isEmpty) {
      throw StateError(
        'Cannot create an order without an authenticated client.',
      );
    }

    // Pre-allocate the document so its id becomes the canonical Order.id.
    final DocumentReference<Map<String, dynamic>> docRef = _orders.doc();

    // The service validates the draft and constructs the initial `pending`
    // order with a single `pending` timeline event (Requirement 8.6). A failing
    // draft throws DraftValidationException before anything is written.
    final Order order = _orderService.buildInitialOrder(
      id: docRef.id,
      clientId: clientId,
      draft: draft,
    );

    await docRef.set(_toDocument(order));

    // Alert administrators of the incoming pre-order (Requirement 8.7).
    await _orderService.notifyAdminsOfNewOrder(order);

    return order;
  }

  @override
  Future<void> updateStatus(
    String orderId,
    OrderStatus status, {
    String? note,
  }) async {
    final DocumentReference<Map<String, dynamic>> docRef = _orders.doc(orderId);
    final DocumentSnapshot<Map<String, dynamic>> snapshot = await docRef.get();
    if (!snapshot.exists) {
      throw StateError('Order "$orderId" was not found.');
    }

    final Order current = _fromSnapshot(snapshot);

    // appendStatusEvent validates the transition and appends one timeline event
    // (Requirements 10A.1, 10A.2, 10A.3). On an illegal transition it throws an
    // InvalidOrderTransitionException WITHOUT mutating `current`; because that
    // happens before the write below, the stored order is left untouched
    // (Requirement 10A.4). We deliberately do not catch it so callers can react.
    final Order updated = _orderService.appendStatusEvent(
      current,
      status,
      note: note,
    );

    await docRef.update(<String, dynamic>{
      'status': updated.status.name,
      'timeline':
          updated.timeline.map((event) => event.toJson()).toList(),
    });

    // Notify the owning client of the status change (Requirement 10A.5).
    await _orderService.notifyClientOfStatusChange(updated, updated.status);
  }

  // ---------------------------------------------------------------------------
  // Reads / streams
  // ---------------------------------------------------------------------------

  @override
  Stream<List<Order>> watchClientOrders(String clientId) {
    return _orders
        .where('clientId', isEqualTo: clientId)
        .snapshots()
        .map(_mapQuerySnapshot);
  }

  @override
  Stream<List<Order>> watchAllOrders({OrderStatus? filter}) {
    Query<Map<String, dynamic>> query = _orders;
    if (filter != null) {
      query = query.where('status', isEqualTo: filter.name);
    }
    return query.snapshots().map(_mapQuerySnapshot);
  }

  @override
  Stream<Order> watchOrder(String orderId) {
    return _orders.doc(orderId).snapshots().map((snapshot) {
      if (!snapshot.exists) {
        throw StateError('Order "$orderId" was not found.');
      }
      return _fromSnapshot(snapshot);
    });
  }

  // ---------------------------------------------------------------------------
  // Firestore <-> Order mapping
  // ---------------------------------------------------------------------------

  List<Order> _mapQuerySnapshot(
    QuerySnapshot<Map<String, dynamic>> snapshot,
  ) =>
      snapshot.docs.map(_fromSnapshot).toList();

  /// Serializes [order] for persistence, dropping the `id` field: the Firestore
  /// document id is the canonical identifier, so storing it in the body would
  /// duplicate (and risk diverging from) the doc id.
  Map<String, dynamic> _toDocument(Order order) {
    final Map<String, dynamic> json = order.toJson();
    json.remove('id');
    return json;
  }

  /// Reconstructs an [Order] from a Firestore document, using the doc id as
  /// [Order.id] and normalizing any [Timestamp] values to ISO-8601 strings so
  /// they round-trip through the generated `fromJson` (which expects strings).
  Order _fromSnapshot(DocumentSnapshot<Map<String, dynamic>> snapshot) {
    final Map<String, dynamic> raw =
        snapshot.data() ?? <String, dynamic>{};
    final Map<String, dynamic> data =
        _normalize(raw) as Map<String, dynamic>;
    data['id'] = snapshot.id;
    return Order.fromJson(data);
  }

  /// Recursively converts Firestore-native temporal types ([Timestamp]/
  /// [DateTime]) into ISO-8601 strings within maps and lists, leaving all other
  /// values untouched. This keeps reads tolerant of documents written with
  /// native Firestore timestamps while still satisfying the string-based
  /// `fromJson` deserializers.
  dynamic _normalize(dynamic value) {
    if (value is Timestamp) {
      return value.toDate().toIso8601String();
    }
    if (value is DateTime) {
      return value.toIso8601String();
    }
    if (value is Map) {
      return value.map(
        (key, dynamic v) => MapEntry(key.toString(), _normalize(v)),
      );
    }
    if (value is List) {
      return value.map(_normalize).toList();
    }
    return value;
  }
}
