import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app/app.dart';
import 'app/providers.dart';
import 'data/sources/local_source.dart';

/// Application entry point.
///
/// Performs the start-up sequence the design's bootstrap depends on, in order:
///
/// 1. Ensure the Flutter binding is initialized (required before any plugin
///    channel calls such as Firebase / Hive / shared_preferences).
/// 2. Initialize Firebase. This is wrapped in a `try/catch` so the app still
///    boots (and remains testable) when platform Firebase config is absent.
/// 3. Initialize Hive for Flutter and open the [LocalSource] (Hive boxes +
///    shared_preferences) — awaited so the cache/prefs are ready before the
///    first frame and the bootstrap reads a valid `seenOnboarding` flag.
/// 4. Run the app inside a [ProviderScope], overriding [localSourceProvider]
///    with the already-initialized [LocalSource] instance (the provider's
///    default throws to force this override — see `app/providers.dart`).
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase. On a configured project, `DefaultFirebaseOptions`
  // would be generated by `flutterfire configure` (lib/firebase_options.dart)
  // and passed as `options: DefaultFirebaseOptions.currentPlatform`. That file
  // is intentionally not committed here, so we call the no-arg initializer and
  // swallow failures: the app must still compile and boot (e.g. in tests or
  // before FlutterFire has been run) without `firebase_options.dart`.
  try {
    await Firebase.initializeApp();
  } catch (error, stackTrace) {
    debugPrint('Firebase initialization skipped/failed: $error\n$stackTrace');
  }

  // Open the local cache + preferences before the first frame so bootstrap can
  // synchronously read the persisted onboarding flag and cached catalog.
  await Hive.initFlutter();
  final localSource = LocalSource();
  await localSource.init();

  runApp(
    ProviderScope(
      overrides: <Override>[
        localSourceProvider.overrideWithValue(localSource),
      ],
      child: const KeyframesApp(),
    ),
  );
}
